version: '3.8'

services:
    postgres:
        image: postgres:13 # Use the official PostgreSQL lastest image
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ecommerce
        ports:
            - "5436:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: